FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
# RUN pip install torch --index-url https://download.pytorch.org/whl/cu122 && pip install -r requirements.txt
RUN pip install torch --index-url https://download.pytorch.org/whl/cu121 && pip install -r requirements.txt

# Expose ports for FastAPI and Streamlit
EXPOSE 8000 8501

# Set environment for GPU access
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility